version: '3.5'

services:

  mysql:
    container_name: 'drp_mysql'
    image: mysql:5.7    
    environment:      
      MYSQL_DATABASE: 'db_drp'              
      MYSQL_USER: 'user'      
      MYSQL_PASSWORD: 'password'      
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - '3308'
    volumes:    
      - ./mysql:/docker-entrypoint-initdb.d/
      - mysql:/var/lib/mysql
    networks:
      - network      
    
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5   
          
 
         
  redis:
    container_name: 'drp_redis'
    image: redis:6.2-alpine                      
    environment:
      REDIS_PWD: 'password123'
     # REDIS_HOSTS: local:redis:6380
    ports:
      - "6379:6379"
    expose:
      - "6379"  
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PWD"
    volumes:
      - redis:/data
    networks:
      - network
      
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5   
      
    depends_on:
      - mysql

      
      
  
  backend:
    container_name: drp_backend
    image: denitiawan/drp-backend:1.0
    environment:           
     
        KAISIR_HOST: 'drp_backend'
        KAISIR_PORT: '8181'

        KAISIR_DB_HOST: 'drp_mysql'
        KAISIR_DB_PORT: '3308'
        KAISIR_DB_USER: 'user'
        KAISIR_DB_PASSWORD: 'password'
        KAISIR_DB_NAME: 'db_drp'

        KAISIR_REDIS_HOST: 'drp_redis'
        KAISIR_REDIS_PORT: '6379'
        KAISIR_REDIS_USERNAME: 'user'
        KAISIR_REDIS_PASSWORD: 'password123'
        
        KAISIR_ALLOWORIGINS_CLIENT_URL: '12345678'
   
      
    ports:      
      - '8181:8181'
    expose:      
      - '8181'      
    networks:
      - network
      
    depends_on:
      - redis
      - mysql
      
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5   
        
 
  web:
    container_name: drp_web
    image: denitiawan/drp-web:latest-prod
    ports:      
      - 80:3000       
    networks:
      - network
    volumes:
      - web_node_modules:/app/node_modules      
    depends_on:
      - redis
      - mysql
      - backend
      
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5   
 
 
 
  
networks:  
  network:    
    driver: bridge

volumes:    
  web_node_modules:
  mysql:
  redis:
    driver: local  
    
     
 